exclude: '^$'
fail_fast: false
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      files: ^src/
      language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
    -   id: check-merge-conflict
    -   id: flake8
        files: ^src/
        args: [--config=.flake8]
-   repo: https://github.com/PyCQA/bandit
    rev: master
    hooks:
    - id: bandit
      files: ^src/
      args: [-ll]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
    -   id: mypy
        files: ^src/
        args: [--no-strict-optional, --ignore-missing-imports]